`timescale 1ns / 1ps

// ============================================================================
// big_muff.sv - EHX Big Muff Pi Fuzz/Sustain Effect Core
//
// Interface matches the existing effect core pattern:
//   sample_en strobe, signed audio_in/audio_out, 8-bit cfg_slice registers.
//
// Register map (via cfg_slice from ctrl_bus):
//   [0] = sustain  (8-bit, fuzz gain:   0x00=min, 0xFF=max)
//   [1] = tone     (8-bit, tone sweep:  0x00=bass, 0x80=scoop, 0xFF=treble)
//   [2] = volume   (8-bit, output vol:  0x00=mute, 0xFF=max)
//   [7] = bypass   (bit 0, managed by axis_effect_slot)
//
// Signal path (models the original EHX Big Muff Pi):
//
//   audio_in --> Gain1 --> Clip1 --> Smooth1 --> Gain2 --> Clip2 --> Smooth2
//                                                                      |
//                                       audio_out <-- Volume <-- Tone (LP+HP)
//
// Each clipping stage is followed by a 2nd-order Butterworth LPF at 10 kHz
// ("smooth" filters).  These model the capacitors in each clipping stage's
// feedback network in the real circuit, which roll off the highest harmonics
// generated by diode clipping.  Without them, the abrupt waveform edges
// create harmonics above Nyquist/2 that fold back as inharmonic aliasing
// noise - audible as background grit when strumming hard.
//
// The 10 kHz cutoff is transparent to audible content (-0.1 dB at 4 kHz)
// while providing -14 dB rejection at 16 kHz and -28 dB at 20 kHz, which
// eliminates the aliasing products.
//
// Clipping: 2-segment piecewise-linear soft-clip, 4:1 compression above
// 37.5% FS knee, ceiling at 50% FS.
//
// Gain (asymmetric, wide range):
//   Stage 1: 1.0x to  4.0x,  Stage 2: 1.5x to 16.0x
//   Total: 1.5x to 64x.  Crest factor: 1.18 (min) to 1.00 (max).
//
// Tone: parallel LP (1200 Hz) + HP (1000 Hz), mid-scoop at centre.
//
// Latency: 1 cycle (sample_en -> audio_out registered)
// ============================================================================

module big_muff #(
    parameter int WIDTH = 24
) (
    input logic clk,
    input logic rst_n,
    input logic sample_en,

    // Audio
    input  logic signed [WIDTH-1:0] audio_in,
    output logic signed [WIDTH-1:0] audio_out,

    // Control registers (8-bit each, directly from cfg_slice)
    input logic [7:0] sustain_val,  // cfg_slice[0]
    input logic [7:0] tone_val,     // cfg_slice[1]
    input logic [7:0] volume_val    // cfg_slice[2]
);

  // =========================================================================
  // Local parameters
  // =========================================================================
  localparam int INT_W = WIDTH + 4;

  // --- Soft-clip thresholds ---
  localparam signed [WIDTH-1:0] CLIP_KNEE = signed'(WIDTH'((3 * (1 << (WIDTH-1))) / 8));  // 0.375 FS
  localparam signed [WIDTH-1:0] CLIP_PEAK = signed'(WIDTH'(1 << (WIDTH - 2)));            // 0.50 FS

  // =========================================================================
  // Filter coefficients - all Q4.20 (COEFF_W=24, FRAC=20)
  // =========================================================================
  // Computed via 2nd-order Butterworth cookbook formulae, verified in Python.
  localparam int COEFF_W = 24;
  localparam int FRAC    = 20;

  // --- Post-clip smoothing: 2nd-order Butterworth LPF, Fc = 10 kHz ---
  // Models the feedback-network capacitors in each clipping stage.
  // Response: -0.1 dB @ 4 kHz, -3 dB @ 10 kHz, -14 dB @ 16 kHz.
  //
  //   b0 =  0.2201947003  b1 =  0.4403894005  b2 =  0.2201947003
  //   a1 = -0.3075663598  a2 =  0.1883451609
  localparam logic signed [COEFF_W-1:0] SM_B0     =  24'sd230891;    //  0.2201947003 * 2^20
  localparam logic signed [COEFF_W-1:0] SM_B1     =  24'sd461782;    //  0.4403894005 * 2^20
  localparam logic signed [COEFF_W-1:0] SM_B2     =  24'sd230891;    //  0.2201947003 * 2^20
  localparam logic signed [COEFF_W-1:0] SM_A1_NEG =  24'sd322507;    //  0.3075663598 * 2^20
  localparam logic signed [COEFF_W-1:0] SM_A2_NEG = -24'sd197494;    // -0.1883451609 * 2^20

  // --- Tone LP: 2nd-order Butterworth LPF, Fc = 1200 Hz ---
  //   b0 =  0.0055427172  b1 =  0.0110854344  b2 =  0.0055427172
  //   a1 = -1.7786317778  a2 =  0.8008026467
  localparam logic signed [COEFF_W-1:0] LP_B0     =  24'sd5812;
  localparam logic signed [COEFF_W-1:0] LP_B1     =  24'sd11624;
  localparam logic signed [COEFF_W-1:0] LP_B2     =  24'sd5812;
  localparam logic signed [COEFF_W-1:0] LP_A1_NEG =  24'sd1865031;
  localparam logic signed [COEFF_W-1:0] LP_A2_NEG = -24'sd839702;

  // --- Tone HP: 2nd-order Butterworth HPF, Fc = 1000 Hz ---
  //   b0 =  0.9115866680  b1 = -1.8231733360  b2 =  0.9115866680
  //   a1 = -1.8153410827  a2 =  0.8310055893
  localparam logic signed [COEFF_W-1:0] HP_B0     =  24'sd955868;
  localparam logic signed [COEFF_W-1:0] HP_B1     = -24'sd1911736;
  localparam logic signed [COEFF_W-1:0] HP_B2     =  24'sd955868;
  localparam logic signed [COEFF_W-1:0] HP_A1_NEG =  24'sd1903523;
  localparam logic signed [COEFF_W-1:0] HP_A2_NEG = -24'sd871373;

  // =========================================================================
  // Per-stage gain from sustain knob
  // =========================================================================
  // Stage 1: 1.0x to  4.0x (Q8.8: 256..1021)
  // Stage 2: 1.5x to 16.0x (Q8.8: 384..4081)
  localparam int GAIN_W = 16;
  logic [GAIN_W-1:0] stage1_gain;
  logic [GAIN_W-1:0] stage2_gain;

  always_comb begin
    stage1_gain = GAIN_W'(16'd256 + ((16'(sustain_val) * 16'd768)  >> 8));
    stage2_gain = GAIN_W'(16'd384 + ((16'(sustain_val) * 16'd3712) >> 8));
  end

  // =========================================================================
  // Soft-clip function
  // =========================================================================
  function automatic logic signed [WIDTH-1:0] soft_clip(
    input logic signed [INT_W-1:0] x
  );
    logic [INT_W-2:0] x_abs;
    logic [INT_W-2:0] y_abs;
    logic signed [WIDTH-1:0] result;

    x_abs = x[INT_W-1] ? (INT_W-1)'(-x) : (INT_W-1)'(x);

    if (x_abs <= (INT_W-1)'(CLIP_KNEE)) begin
      result = x[WIDTH-1:0];
    end else begin
      y_abs = (INT_W-1)'(CLIP_KNEE) + ((x_abs - (INT_W-1)'(CLIP_KNEE)) >> 2);
      if (y_abs > (INT_W-1)'(CLIP_PEAK))
        y_abs = (INT_W-1)'(CLIP_PEAK);
      result = x[INT_W-1] ? -WIDTH'(y_abs) : WIDTH'(y_abs);
    end

    return result;
  endfunction

  // =========================================================================
  // Clipping stage 1 + post-clip smoothing
  // =========================================================================
  logic signed [INT_W-1:0] stage1_gained;
  logic signed [WIDTH-1:0] stage1_clipped;
  logic signed [WIDTH-1:0] stage1_smooth;

  always_comb begin
    stage1_gained  = INT_W'((longint'(audio_in) * longint'(signed'({1'b0, stage1_gain}))) >>> 8);
    stage1_clipped = soft_clip(stage1_gained);
  end

  biquad_tdf2 #(
      .DATA_W (WIDTH),
      .COEFF_W(COEFF_W),
      .FRAC   (FRAC)
  ) u_smooth1 (
      .clk   (clk),
      .rst_n (rst_n),
      .en    (sample_en),
      .x_in  (stage1_clipped),
      .y_out (stage1_smooth),
      .b0    (SM_B0),
      .b1    (SM_B1),
      .b2    (SM_B2),
      .a1_neg(SM_A1_NEG),
      .a2_neg(SM_A2_NEG)
  );

  // =========================================================================
  // Clipping stage 2 + post-clip smoothing
  // =========================================================================
  // Stage 2 input is the smoothed output from stage 1 (previous sample's
  // biquad output, stable at sample_en edge - same 1-sample latency model).
  logic signed [INT_W-1:0] stage2_gained;
  logic signed [WIDTH-1:0] stage2_clipped;
  logic signed [WIDTH-1:0] stage2_smooth;

  always_comb begin
    stage2_gained  = INT_W'((longint'(stage1_smooth) * longint'(signed'({1'b0, stage2_gain}))) >>> 8);
    stage2_clipped = soft_clip(stage2_gained);
  end

  biquad_tdf2 #(
      .DATA_W (WIDTH),
      .COEFF_W(COEFF_W),
      .FRAC   (FRAC)
  ) u_smooth2 (
      .clk   (clk),
      .rst_n (rst_n),
      .en    (sample_en),
      .x_in  (stage2_clipped),
      .y_out (stage2_smooth),
      .b0    (SM_B0),
      .b1    (SM_B1),
      .b2    (SM_B2),
      .a1_neg(SM_A1_NEG),
      .a2_neg(SM_A2_NEG)
  );

  // =========================================================================
  // Post-clip level restore (×2)
  // =========================================================================
  // Clipped signal peaks at ±CLIP_PEAK (50% FS).  Shift up to use full
  // dynamic range for the tone filters.
  logic signed [WIDTH-1:0] clipped_norm;

  always_comb begin
    if (stage2_smooth >= CLIP_PEAK)
      clipped_norm = {1'b0, {(WIDTH-1){1'b1}}};
    else if (stage2_smooth <= -CLIP_PEAK)
      clipped_norm = {1'b1, {(WIDTH-1){1'b0}}};
    else
      clipped_norm = WIDTH'(stage2_smooth <<< 1);
  end

  // =========================================================================
  // Tone section: parallel LP / HP biquad filters
  // =========================================================================
  logic signed [WIDTH-1:0] tone_lp_out;
  logic signed [WIDTH-1:0] tone_hp_out;

  biquad_tdf2 #(
      .DATA_W (WIDTH),
      .COEFF_W(COEFF_W),
      .FRAC   (FRAC)
  ) u_tone_lp (
      .clk   (clk),
      .rst_n (rst_n),
      .en    (sample_en),
      .x_in  (clipped_norm),
      .y_out (tone_lp_out),
      .b0    (LP_B0),
      .b1    (LP_B1),
      .b2    (LP_B2),
      .a1_neg(LP_A1_NEG),
      .a2_neg(LP_A2_NEG)
  );

  biquad_tdf2 #(
      .DATA_W (WIDTH),
      .COEFF_W(COEFF_W),
      .FRAC   (FRAC)
  ) u_tone_hp (
      .clk   (clk),
      .rst_n (rst_n),
      .en    (sample_en),
      .x_in  (clipped_norm),
      .y_out (tone_hp_out),
      .b0    (HP_B0),
      .b1    (HP_B1),
      .b2    (HP_B2),
      .a1_neg(HP_A1_NEG),
      .a2_neg(HP_A2_NEG)
  );

  // =========================================================================
  // Tone blend
  // =========================================================================
  logic signed [INT_W-1:0] tone_mixed;
  logic signed [WIDTH-1:0] tone_out;

  always_comb begin
    logic [8:0] lp_weight;
    logic [7:0] hp_weight;

    hp_weight = tone_val;
    lp_weight = 9'd256 - 9'(tone_val);

    tone_mixed = INT_W'(
        (longint'(tone_lp_out) * longint'(signed'({1'b0, lp_weight})) +
         longint'(tone_hp_out) * longint'(signed'({1'b0, hp_weight}))) >>> 8
    );
  end

  saturate #(
      .IN_W (INT_W),
      .OUT_W(WIDTH)
  ) u_sat_tone (
      .din (tone_mixed),
      .dout(tone_out)
  );

  // =========================================================================
  // Volume control
  // =========================================================================
  logic signed [INT_W-1:0] vol_scaled;
  logic signed [WIDTH-1:0] vol_out;

  always_comb begin
    vol_scaled = INT_W'((longint'(tone_out) * longint'({1'b0, volume_val})) >>> 8);
  end

  saturate #(
      .IN_W (INT_W),
      .OUT_W(WIDTH)
  ) u_sat_vol (
      .din (vol_scaled),
      .dout(vol_out)
  );

  // =========================================================================
  // Registered output (1-cycle latency)
  // =========================================================================
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) audio_out <= '0;
    else if (sample_en) audio_out <= vol_out;
  end

endmodule